databases:
  - name: color-shape_fashion_DB
    databaseName: color-shape_fashion_db
    user: color-shape_fashion
    region: singapore

services:
  - type: web
    name: color-shape_fashion
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: color-shape_fashion_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false